import fs from "fs/promises";
import path from "path";
import Head from "next/head";
import Layoute from "../components/layout/Layoute";
import Loading from "../components/loading";
import Slider from "../components/Slider"
import Album1 from "../components/Album1"
import Invitation from "../components/Invitation";
import Album2 from "../components/Album2";
import Description from "../components/Description";
import Album3 from "../components/Album3";
import Suggestion from "../components/Suggestion";


export default function Home({ datas }) {
  return (
    <>
      <Head>
        <title>خانه</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

            <>
            <Slider />
             <Album1 />
             <Invitation/>
             <Album2/>
           <Description/>
            <Album3 />
             <Suggestion />
            
            </>

      </main>
    </>
  );
}

export async function getStaticProps(context) {
  const findedPath = path.join("src","db.json")
  const dataJson = await fs.readFile(findedPath)
  const datas = JSON.parse(dataJson)
  return {
    props: { datas },
  };
}
